### ISSUE TITLE
Self-Referential Substitutions don't work

### ISSUE THREAD

**Issue by troizky** [puppetlabs/cpp-hocon#105]
I'm using the example from documentation: https://github.com/lightbend/config/blob/master/HOCON.md#examples-of-self-referential-substitutions
```
A self-reference resolves to the value "below" even if it's part of a path expression. So for example:

foo : { a : { c : 1 } }
foo : ${foo.a}
foo : { a : 2 }

Here, ${foo.a} would refer to { c : 1 } rather than 2 and so the final merge would be { a : 2, c : 1 }.
Recall that for a field to be self-referential, it must have a substitution or value concatenation as its value. If a field has an object or array value, for example, then it is not self-referential even if there is a reference to the field itself inside that object or array.
```
And I'm getting crash:
`
terminate called after throwing an instance of 'hocon::bug_or_broken_exception'
  what():  resolve_substitutions() did not give us a resolved object
`
Also I'm getting crash in cases below:
```
a = {aa = abba}
a.aa = mama
b = ${a} { bb = mia }
# Everything below is failing
b.aa = mea
b.bb = culpa
b = { aa = mea, bb = culpa }
c = ${b.aa}
c = ${b.bb}
```
Looks like this library implementation doesn't follow the HOCON documentation...

**Comment by MikaelSmith** [comment]
The implementation is incomplete. I would appreciate any help finishing it for those cases.

**Comment by troizky** [comment]
Even the simplest testcase does not work:
```
  "a": {
    "b": 27
  },
  "obj": ${a}
  "val": ${obj.b}
```
Maybe this one is easier to fix?

**Comment by MikaelSmith** [comment]
That is likely [HC-73](https://tickets.puppetlabs.com/browse/HC-73). I'll take a quick look to see if I can figure out what's wrong, but don't have a ton of time to spend on it before I'm on vacation for 2 weeks.

**Comment by MikaelSmith** [comment]
This library was implemented to closely mirror the structure of https://github.com/lightbend/config. So tracing the exception I get with your simple test case back to https://github.com/puppetlabs/cpp-hocon/blob/master/lib/src/values/config_reference.cc#L75 and comparing to https://github.com/lightbend/config/blob/master/config/src/main/java/com/typesafe/config/impl/ConfigReference.java#L70, it looks like the fallback code at https://github.com/puppetlabs/cpp-hocon/blob/master/lib/src/values/config_reference.cc#L61 wasn't implemented. I'll try that out.

**Comment by MikaelSmith** [comment]
It looks like this might have actually been fixed recently in config v1.3.2. So there's some work to incorporate the fixes added.

**Comment by troizky** [comment]
I think the problem is here: https://github.com/puppetlabs/cpp-hocon/blob/master/lib/src/resolve_source.cc#L152  The method **config_object::attempt_peek_with_partial_resolve** returns pointer to *config_value*, but later I see a *dynamic_pointer_cast* to *config_object* that fails forever.

**Comment by troizky** [comment]
I've found bug in https://github.com/puppetlabs/cpp-hocon/blob/master/lib/src/values/simple_config_object.cc#L32, must be checking for non-empty.
Corresponding line in Java project: https://github.com/lightbend/config/blob/master/config/src/main/java/com/typesafe/config/impl/SimpleConfigObject.java#L364

**Comment by troizky** [comment]
Also found that method **config_delayed_merge_object::resolve_substitutions** was not implemented like here: https://github.com/lightbend/config/blob/master/config/src/main/java/com/typesafe/config/impl/ConfigDelayedMergeObject.java#L53

After fixing that I'm getting an exception '*should not be reached (merging non-simple_config_object)*' in **simple_config_object::merged_with_object** on parsing following config:
```
    a = {aa = mama, bb = mia}
    b = ${a}
    b.aa = mea
    # below is failing
    b.bb = culpa
```

**Comment by troizky** [comment]
One more bug in https://github.com/puppetlabs/cpp-hocon/blob/master/lib/inc/internal/values/config_delayed_merge_object.hpp#L10, class **config_delayed_merge_object** did not inherit from class **unmergeable** https://github.com/lightbend/config/blob/master/config/src/main/java/com/typesafe/config/impl/ConfigDelayedMergeObject.java#L21

**Comment by troizky** [comment]
Here is my suggested patch:
[cpp-hocon.patch.gz](https://github.com/puppetlabs/cpp-hocon/files/2013162/cpp-hocon.patch.gz)

**Comment by troizky** [comment]
Here is my suggested patch:
[cpp-hocon.patch.gz](https://github.com/puppetlabs/cpp-hocon/files/2013247/cpp-hocon.patch.gz)

**Comment by troizky** [comment]
Open Merge Request https://github.com/puppetlabs/cpp-hocon/pull/106

**Comment by MikaelSmith** [comment]
Thanks for digging into this! I'll work on reviewing the PRs.
