### ISSUE TITLE
Fails to build with Boost 1.72

### ISSUE THREAD

**Issue by jbeich** [puppetlabs/cpp-hocon#118]
## Describe the Bug
Regressed by boostorg/filesystem@68ec5b1fb66b. From [error log](https://github.com/puppetlabs/cpp-hocon/files/3772475/cpp-hocon-0.2.1_5.log):
```
[100%] Linking CXX executable ../../bin/libcpp-hocon_test
ld: error: undefined symbol: typeinfo for boost::filesystem::filesystem_error
>>> referenced by parseable.cc
>>>               ../CMakeFiles/libprojectsrc.dir/src/parseable.cc.o:(.data+0x0)
c++: error: linker command failed with exit code 1 (use -v to see invocation)
```

## Expected Behavior
Builds fine

## Steps to Reproduce
1. `cmake .`
2. `make`

## Environment
 - Boost 1.72 [snapshot](https://dl.bintray.com/boostorg/master/boost_1_72_0-snapshot.tar.bz2) ([downstream](https://reviews.freebsd.org/D22136))
 - FreeBSD 12.1 amd64

## Additional Context
Can be worked around by removing the following line
https://github.com/puppetlabs/cpp-hocon/blob/cdfa711eccecb09c209bd7afa6a500d957b9042a/lib/CMakeLists.txt#L94

**Comment by jbeich** [comment]
@Lastique, do you have a clue?

```
$ nm --demangle boost-1.71.0/lib/libboost_filesystem.so | grep type.\*filesystem_error
nm: /tmp/boost-1.71.0/usr/local/lib/libboost_filesystem.so: no symbols

$ nm --demangle boost-1.72.alpha/lib/libboost_filesystem.so | grep type.\*filesystem_error
000000000001c0d0 D typeinfo for boost::filesystem::filesystem_error
0000000000007c44 R typeinfo name for boost::filesystem::filesystem_error
```

**Comment by Lastique** [comment]
No, not really. From `nm` output the necessary symbols are exported from libboost_filesystem.so. Maybe your `libcpp-hocon_test` executable doesn't link with it?

**Comment by jbeich** [comment]
Indeed. At first I've only tried passing `libboost_filesystem.so` manually which didn't help but after adding `filesystem` to `find_package(Boost)` line in CMakeLists.txt the error disappeared.
