### ISSUE TITLE
releases aren't buildable

### ISSUE THREAD

**Issue by ccaviness** [puppetlabs/cpp-hocon#87]
The release tarballs only have the `lib` and `include` directories, but not top level files such as (critically) `CMakeLists.txt`.

    $ curl -sL https://github.com/puppetlabs/cpp-hocon/releases/download/0.1.4/cpp-hocon.tar.gz | tar tz | grep CMakeLists.txt
    $

**Comment by ccaviness** [comment]
.. I think this is working as intended; `leatherman` project's releases are the same. I'll just use the source code tarballs.

**Comment by MikaelSmith** [comment]
That is "intended". They're not well-labeled, but they're binary distributions intended for use down-stream in Travis and AppVeyor CI.
